# Generated by Django 3.2.3 on 2021-05-26 02:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afluente',
            fields=[
                ('codRio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAfluente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Afluente',
                'verbose_name_plural': 'Afluentes',
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('ventas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Boya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Boya', models.CharField(max_length=50)),
                ('Latitud', models.CharField(max_length=50)),
                ('Longitud', models.CharField(max_length=50)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Boya',
                'verbose_name_plural': 'Boyas',
            },
        ),
        migrations.CreateModel(
            name='Circutio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='Dano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('birthyear', models.DateTimeField()),
                ('birthplace', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Sensor', models.CharField(max_length=40)),
                ('Voltaje', models.IntegerField()),
                ('Referencia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='boyaapp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicion', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('codBoya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boyaapp.boya')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Fecha', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codDano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyaapp.circutio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCircuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyaapp.circutio')),
                ('codMantenimeinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyaapp.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='circutio',
            name='codSensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boyaapp.sensor'),
        ),
        migrations.AddField(
            model_name='boya',
            name='codCircuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyaapp.circutio'),
        ),
        migrations.AddField(
            model_name='boya',
            name='codDepert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyaapp.departamento'),
        ),
        migrations.AddField(
            model_name='boya',
            name='codMuicipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyaapp.municipios'),
        ),
        migrations.AddField(
            model_name='boya',
            name='codRio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boyaapp.afluente'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('codBoya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boyaapp.boya')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
